title: Mark Ayers
description: |
  a human being, being human;<br>
  intending to sleep, move, eat, grow, & share;<br>
  while I love, laugh, cry, & eventually, die.
url: https://philoserf.com/
author:
  name: Mark Ayers
  email: mark@philoserf.com
  handle: philoserf

job:
  employer: Hypori
  title: Senior Site Reliability Engineer

remote_theme: benbalter/retlab

contact_links:
  - name: Email
    url: "mailto:mark@philoserf.com"
    icon: fa-solid fa-envelope
  - name: Add to contacts
    url: https://philoserf.com/vcard.vcf
    icon: fa-solid fa-address-card
  - name: LinkedIn
    url: https://www.linkedin.com/in/markpaulayers
    icon: fa-brands fa-linkedin
  - name: GitHub
    url: https://github.com/philoserf
    icon: fa-brands fa-github
  - name: Mastodon
    url: https://pkm.social/@philoserf
    icon: fa-brands fa-mastodon

nav_pages:
  - about.md
  - now.md

footer_pages:
  - about.md
  - contact.md
  - colophon.md
  - now.md

timezone: America/New_York
encoding: UTF-8
lang: en-US
branch: main

exclude:
  - _site/
  - .task/
  - .env
  - .gitattributes
  - .gitignore
  - .markdownlint.yaml
  - .yamllint
  - Brewfile
  - Brewfile.lock.json
  - check-dns
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - taskfile.yaml

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
