# https://taskfile.dev
version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - prettier --write --ignore-unknown --list-different .
      - bundle update
      - markdownlint --fix .
      - yamllint .
      - task: doctor
      - task: build
      - task: clean

  bundle:
    sources:
      - "Gemfile.local"
    generates:
      - "Gemfile.lock"
    cmds:
      - cp Gemfile.local Gemfile
      - bundle update

  doctor:
    cmds:
      - bundle exec jekyll doctor

  build:
    cmds:
      - bundle exec jekyll build

  clean:
    cmds:
      - bundle exec jekyll clean

  serve:
    cmds:
      - bundle exec jekyll serve --livereload

  bootstrap:
    deps:
      - bundle
    status:
      - brew bundle check
    cmds:
      - brew bundle
