name: lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            *.md
            **/*.md
      - uses: actionsx/prettier@v3
        with:
          args: --check --ignore-unknown .
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install yamllint
          yamllint .
